### ISSUE TITLE
Make it so buttons remain selected (i.e. default to weekday and am peak coloured in)

### ISSUE THREAD

**Issue by chmnata** [CityofToronto/bdit_traffic_dashboard#35]

**Comment by chmnata** [comment]
Changing all radiobuttons to buttons requires a lot of changes in the app.callback functions. Since radiobuttons always return a value (which is used in other functions), and buttons does not, we will have to change those other functions to register what was click as well as what was last clicked. I don't feel like its worth to spend the amount of time and work needed to make a button looks selected in this current sprint, maybe we can revisit this later when dash  add a css for this. 

We could do this instead: 
![image](https://user-images.githubusercontent.com/46324452/65254082-b74bf180-dac9-11e9-8896-7e075c9da299.png) 
so we can still keep track of what item was selected 


![image](https://user-images.githubusercontent.com/46324452/65255330-ae5c1f80-dacb-11e9-8f3c-75c2cf56fe76.png)

**Comment by radumas** [comment]
If we use [Dash Bootstrap Components](https://dash-bootstrap-components.opensource.faculty.ai/l/components/input#radioitems-input), the `<input>`  and `<label>` html tags are in the right order, unlike Dash-Core-Componets (see https://github.com/plotly/dash-core-components/issues/123)  so we would be able to style the radio buttons using other themes

**Comment by chmnata** [comment]
Changed app.layout with dbc and use `dbc.RadioItems` instead of dcc. Along with css from this issue 
https://github.com/facultyai/dash-bootstrap-components/issues/222#issuecomment-513201494

![image](https://user-images.githubusercontent.com/46324452/65627067-98070580-df9c-11e9-81e5-25fc3fb40b1b.png)
