### ISSUE TITLE
Test 7 tabs

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_traffic_dashboard#53]
See if it looks ridiculous on mobile.

**Comment by chmnata** [comment]
![image](https://user-images.githubusercontent.com/46324452/69880048-fbf8c380-1296-11ea-949a-d49996e1f9e1.png)
galaxy s5:
![image](https://user-images.githubusercontent.com/46324452/69880160-42e6b900-1297-11ea-8ba3-f1d0582d209f.png)
iphone 5:
![image](https://user-images.githubusercontent.com/46324452/69880190-598d1000-1297-11ea-8a6f-a0aca131f236.png)
iphone 6,7,8:
![image](https://user-images.githubusercontent.com/46324452/69880215-6a3d8600-1297-11ea-9a3b-69799ac1a355.png)
ipad:
![image](https://user-images.githubusercontent.com/46324452/69880233-74f81b00-1297-11ea-886a-1e59fbfdeec4.png)

**Comment by chmnata** [comment]
the blue line moving up and down is annoying and confusing
![7_tabs](https://user-images.githubusercontent.com/46324452/69880569-3e6ed000-1298-11ea-8354-ec5ab9ecfdf4.gif)
