### ISSUE TITLE
Fix generate table function to make wellington show up 

### ISSUE THREAD

**Issue by chmnata** [CityofToronto/bdit_traffic_dashboard#57]
Only Wellington's table is not updating, graph is updating though. Getting `Keyerror: Eastbound` error, investigate, fix and document here.

![image](https://user-images.githubusercontent.com/46324452/70064422-82731500-15b7-11ea-8a1b-077aab56af80.png)

**Comment by chmnata** [comment]
Just need to catch `KeyError` for both `baseline_val` and `after_val` apparently.....

**Comment by radumas** [comment]
> Just need to catch `KeyError` for both `baseline_val` and `after_val` apparently.....

Weird I thought that was already how this was being dealt with for Adelaide and Richmond (and Wellington before....)

**Comment by chmnata** [comment]
I think it is because the table for adelaide, richmond, eastern goes through Eastbound (not nan) and then Westbound (nan), and the error was raised after it returns the first row of data? And maybe since Adelaide is the defaulted street for this tab, the table will be updated without error. 

> > Just need to catch `KeyError` for both `baseline_val` and `after_val` apparently.....
> 
> Weird I thought that was already how this was being dealt with for Adelaide and Richmond (and Wellington before....)
