### ISSUE TITLE
Investigate screenshot/create document from app

### ISSUE THREAD

**Issue by chmnata** [CityofToronto/bdit_traffic_dashboard#62]

**Comment by chmnata** [comment]
Print button:
https://dash-gallery.plotly.host/dash-vanguard-report/

**Comment by chmnata** [comment]
pdfkit:
https://micropyramid.com/blog/how-to-create-pdf-files-in-python-using-pdfkit/

**Comment by chmnata** [comment]
https://plot.ly/python/v3/pdf-reports/

**Comment by chmnata** [comment]
print layout
![image](https://user-images.githubusercontent.com/46324452/70468973-1d775d80-1a96-11ea-8f15-ea7e897220b4.png)

**Comment by chmnata** [comment]
current print layout without footer and header
![image](https://user-images.githubusercontent.com/46324452/70546833-f96f5700-1b3d-11ea-9ad6-581adef30602.png)

**Comment by radumas** [comment]
Can we remove the box highlighting the selected street in the table?
